### ISSUE TITLE
Using SpringMVC frameworker, how to configure the netflix?

### ISSUE THREAD

**Issue by zjw186** [Oreste-Luci/netflix-oss-example#2]
In my project, the frameworker is spring mvc, there is no main function, how can I configure the netflix?

**Comment by Oreste-Luci** [comment]
I'm sorry but I don't understand your question. Are you having problem running the example?

**Comment by zjw186** [comment]
@Oreste-Luci  I mean the framework of my project is spring mvc, how can i register the client to eureka server?

**Comment by dinkarthakur** [comment]
hi,

I guess you just need to bootify it, add or you can try adding
@configuration /@ component class and add @SpringEurekaClient there.
Have not tried it but i guess this should work.

Regards
Dinkar Thakur

On Mon, May 30, 2016 at 2:15 PM, zjw186 notifications@github.com wrote:

> @Oreste-Luci https://github.com/Oreste-Luci I mean the framework of my
> project is spring mvc, how can i register the client to eureka server?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Oreste-Luci/netflix-oss-example/issues/2#issuecomment-222443788,
> or mute the thread
> https://github.com/notifications/unsubscribe/AB_QZoU8jFpM4ZbsXJRfr6XVa9SMhv5Pks5qGqOigaJpZM4Ipc8H
> .

## 

Dinkar Thakur

**Comment by Oreste-Luci** [comment]
I haven't tried it without spring boot. But I guess if you add the dependency for EurekaClient (the jars) you should be able to register in Eureka. Also Eureka exposes an API that can be used to register and query the service directory.
