### ISSUE TITLE
Java11 - Cannot run any jar (tried eureka-server, config-service and service-c)

### ISSUE THREAD

**Issue by Muzietto** [Oreste-Luci/netflix-oss-example#3]
I must be having some library version mis-alignment, but I tried to compile & run three different pieces of your architecture without any success.

These are my settings:
![image](https://user-images.githubusercontent.com/2652413/66830237-49bea400-ef55-11e9-9691-942e491810f0.png)

I am using your files without any modification whatsoever. I'm on Ubuntu 18.04.

Please ask me any further information. I understand the project is old, but I'd expect to be able to run it. The pom files should provide the right Spring components, am I correct?

Here follows some detail about the issues:

## issue 1: eureka-server
- no problems during maven run
- `java -jar` fails with: 
  + java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.bootstrap.encrypt.EncryptionBootstrapConfiguration
  ....
  + Caused by: java.lang.IllegalStateException: Failed to introspect annotations: class org.springframework.cloud.bootstrap.encrypt.EncryptionBootstrapConfiguration 
  ....
  + Caused by: java.lang.ClassNotFoundException: org.springframework.security.rsa.crypto.RsaSecretEncryptor

## issue 2: config-service:
- no problems during maven run
- `java -jar` fails with:
  + org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
  ...
  + Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException

## issue 3: service-c --> same as eureka-server
- no problems during maven run
- `java -jar` fails with: 
  + java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.bootstrap.encrypt.EncryptionBootstrapConfiguration
  ....
  + Caused by: java.lang.IllegalStateException: Failed to introspect annotations: class org.springframework.cloud.bootstrap.encrypt.EncryptionBootstrapConfiguration 
  ....
  + Caused by: java.lang.ClassNotFoundException: org.springframework.security.rsa.crypto.RsaSecretEncryptor

**Comment by Muzietto** [comment]
Got some solutions. Closing the issue. In the next days I will propose you a PR.

**Comment by Oreste-Luci** [comment]
Good that you could solve it. Unfortunately, I haven't updated this repo to the latest versions.
